version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
